# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTEwYWQxZGY3OWY3YzhmYjA5ZGEyNjRmZmY3MjI4ZmI4YzdmYTY3ZTExNmQ0NDkyZGQ3OTFiZDVkOTAxY2E2NzQ1ZWFmNWExMDdkN2I0YmNkNDdkMWMzYThlZmI2M2M4NTExMzdkZmI3NDNlMzEwYmY3NzY5ZWVlNDEwZTNhNjE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
